from typing import Dict, List
from pydantic import BaseModel, Field
from enum import Enum


class SourceType(Enum):
    RESEARCH_ARTICLE = "research_article"
    TEXTBOOK = "textbook"


class Citation(BaseModel):
    title: str
    authors: list[str]
    publication_date: str
    publisher: str


class Source(BaseModel):
    id: str
    content: str
    source_type: SourceType
    citation: Citation


class Reference(BaseModel):
    id: str
    source_id: str = Field(
        description="References the `Source.id` field of the source that this reference points to"
    )
    source_citation: Citation = Field(
        description="The citation of the source this reference comes from."
    )
    statement: str = Field(description="The statement that we are referencing")
    context: str = Field(
        description="The surrounding context of the statement that we are referencing"
    )


class Node(BaseModel):
    id: str
    premises: List[str] = Field(
        description="References the `Node.id` field of this node's premise nodes"
    )
    conclusion: str = Field(
        description="The logical statement that this node asserts given its premises."
    )
    justification: str = Field(
        description="An argument for why the references support this conclusion, or why this node is trivial enough to be immediately accepted."
    )
    reference_search_terms: List[str] = Field(
        default_factory=list,
        description="The list of search terms used to find supporting references",
    )
    references: List[str] = Field(
        default_factory=list, description="References the `Reference.id` field"
    )
    is_refutation: bool = Field(
        default=False, description="Was generated by the refuter agent"
    )


class Graph(BaseModel):
    nodes: Dict[str, Node] = Field(
        default_factory=dict, description="Maps `Node.id`s to the corresponding nodes"
    )
    references: Dict[str, Reference] = Field(
        default_factory=dict,
        description="Maps `Reference.id`s to the corresponding References",
    )
